TODO:
- [ ] PARALLELIZE PRECOMPUTING
- [x] PLOTTING CON PYTHON
- [x] SCRIPT C/PYTHON ESTERNO CHE CHIAMI IN LOOP IL MAIN PER CONFRONTARE VARI ALGORITMI (ES PRENDI LO STDOUT PER LEGGERE I COSTI TROVATI)